### PR TITLE
Support SSR. Don't load client when window is not available.

### PR DESCRIPTION
**Pull request by vernondegoede**

### CODE REVIEW

**Comment by JeffersonFilho** [comment]
Awesome! Thanks for taking your time to improve this package! As soon I get a decent internet on my laptop I will merge this and release a new version of the package on the npm!

**Comment by vernondegoede** [comment]
@JeffersonFilho Did you find time to take a closer look at this change? Would be great if this could be merged & published soon.

**Comment by vernondegoede** [comment]
This does not solve the problem entirely, actually. 

`window` is not referenced anymore from the package itself, which is great. However, this package does use `style-loader`, which assumes that `window` is available (in `build/index.js`: `return window&&document&&document.all&&!window.atob`

In order to fully support SSR, we could try to use the isomorphic style loader (https://github.com/creeperyang/iso-morphic-style-loader).

https://stackoverflow.com/questions/47481736/window-is-not-defined-with-css-loader

**Comment by JeffersonFilho** [comment]
Interesting, I will have look at it!

**Pull request merged**
